<project xmlns="http://maven.apache.org/POM/4.0.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    
    <groupId>unimilk.playertracker</groupId>
    <artifactId>PlayerTracker</artifactId>
    <version>4.2.0</version>
    <packaging>pom</packaging>

    <name>PlayerTracker</name>
    <description>PlayerTracker is an esay-to-use plugin for ops in Minecraft servers to get to know the coordinary and status of online players.</description>

    <properties>
        <!-- Set Java Version Here -->
        <java.version>15</java.version>
        <java.target.version>1.8</java.target.version>
        <java.release.version>8</java.release.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <modules>
        <module>playertracker-api</module>
        <module>playertracker-common</module>
        <module>playertracker-v1_13_15</module>
        <module>playertracker-v1_16_21</module>
        <module>playertracker-assembly</module>
    </modules>

    <build>
        <plugins>
            <!-- Make sure the target compatible with Java 8 -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.target.version}</target>
                    <release>${java.release.version}</release>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
