<project xmlns="http://maven.apache.org/POM/4.0.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    
    <groupId>unimilk.playertracker</groupId>
    <artifactId>PlayerTracker</artifactId>
    <version>4.1.0</version>
    <packaging>pom</packaging>

    <name>PlayerTracker</name>
    <description>PlayerTracker is an esay-to-use plugin for ops in Minecraft servers to get to know the coordinary and status of online players.</description>

    <properties>
        <!-- 使用 Java 17 编译 -->
        <java.version>17</java.version>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <modules>
        <module>playertracker-api</module>
        <module>playertracker-common</module>
        <module>playertracker-v1_13_15</module>
        <module>playertracker-v1_16_21</module>
        <module>playertracker-assembly</module>
    </modules>
</project>
