<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>unimilk.playertracker</groupId>
        <artifactId>PlayerTracker</artifactId>
        <version>4.1.0</version>
    </parent>

    <artifactId>playertracker-v1_16_21</artifactId>
    <packaging>jar</packaging>

    <name>PlayerTracker v1.16–1.21</name>

    <dependencies>
        <dependency>
            <groupId>unimilk.playertracker</groupId>
            <artifactId>playertracker-common</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>unimilk.playertracker</groupId>
            <artifactId>playertracker-api</artifactId>
            <version>${project.version}</version>
        </dependency>

        <!-- Spigot 1.16 API -->
        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot-api</artifactId>
            <version>1.16.3-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>
