name: PlayerTracker
main: unimilk.playertracker.PlayerTracker
authors:
  - unimilk
version: 3.1.0
api-version: 1.19
commands:
  playertracker:
    description: playertracker插件主命令
    usage: /playertracker <subcommands>
    permission: playertracker.use
    aliases: [pt]
permissions:
  playertracker.admin:
    description: 允许管理员修改插件配置
    default: op
  playertracker.use:
    description: 允许玩家使用 /pt 相关命令
    default: op
  playertracker.view:
    description: 允许玩家使用 /pt viewer 命令
    default: op
