<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    
    <parent>
        <groupId>unimilk.playertracker</groupId>
        <artifactId>PlayerTracker</artifactId>
        <version>4.2.0</version>
    </parent>

    <artifactId>playertracker-common</artifactId>
    <packaging>jar</packaging>

    <name>PlayerTracker Common</name>
    <properties>
        <spigot.version>1.13.1-R0.1-SNAPSHOT</spigot.version>
    </properties>

    <dependencies>
        <!-- Import playertracker-api Module -->
        <dependency>
            <groupId>unimilk.playertracker</groupId>
            <artifactId>playertracker-api</artifactId>
            <version>${project.version}</version>
        </dependency>

        <!-- Spigot API -->
        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot-api</artifactId>
            <version>${spigot.version}</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

</project>